Fix compile error when building unit tests
This bug is a typo that was unchecked because I've been using horizontal
shooter to test the untech-editor instead of the untech-engine
unit_tests for the last few weeks.

../tools/bass-untech/bass/out/bass-untech -strict -o bin/unit-tests.sfc -sym bin/unit-tests.sym src/unit-tests.asm
error: malformed expression: {EntityStruct}.Animations.animation
src/tests/entity/entities/delete-if-animation-ends.inc:19:1: lda.w #{EntityStruct}.Animations.animation
bass: assembly failed
make: *** [../GNUmakefile.in:72: bin/unit-tests.sfc] Error 1
make: *** Deleting file 'bin/unit-tests.sfc'